[deploy]
bucket = 'cfn-artifacts-cloudbootcamp'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://cruddursn.net'
EnvBackendUrl = 'https://api.cruddursn.net'